2022-05-16 17:15:53,340 - list index out of range
Traceback (most recent call last):
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\connect_sql.py", line 163, in <module>
    if row[0][0] == chave:
IndexError: list index out of range
