2022-07-26 18:17:03,998 - null value in column "chave_nf" violates not-null constraint
DETAIL:  Failing row contains (21, recebimento, null, 2001-01-01, null, Célula sem dado, Armazem, 6, 2022-07-26 18:16:00).
Traceback (most recent call last):
  File "C:/Users/allan.mesquita/OneDrive - NTT/Documents/Projetos/Automacao_Evidencias/Script/Test_Zone/main_qualidade2.py", line 125, in <module>
    resultado = validacao.rec_validation(aba, qtd_linhas)
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_Zone\Modulos\validacao.py", line 297, in rec_validation
    print(save.connect())
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_Zone\Modulos\class_erros.py", line 208, in connect
    cur.execute(
psycopg2.errors.NotNullViolation: null value in column "chave_nf" violates not-null constraint
DETAIL:  Failing row contains (21, recebimento, null, 2001-01-01, null, Célula sem dado, Armazem, 6, 2022-07-26 18:16:00).

