2022-07-29 16:05:29,037 - 'Error' object is not iterable
Traceback (most recent call last):
  File "C:/Users/allan.mesquita/OneDrive - NTT/Documents/Projetos/Automacao_Evidencias/Script/Test_Zone/main_qualidade2.py", line 127, in <module>
    resultado = validacao.exp_validacao(aba, qtd_linhas)
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_Zone\Modulos\validacao.py", line 522, in exp_validacao
    for chaves in dict_chaves:
TypeError: 'Error' object is not iterable
