2022-05-10 12:03:42,239 - [WinError 3] The system cannot find the path specified: 'C:\\Users\\allan.mesquita\\NTT\\@AM BR Services and Operations - Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\Testes\\01 Processamento\\202204051510 33220305437734000580550010000026611100018356_Expedição.xlsx' -> 'C:\\Users\\allan.mesquita\\NTT\\@AM BR Services and Operations - Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\03 Erro\\202204051510 33220305437734000580550010000026611100018356_Expedição.xlsx'
Traceback (most recent call last):
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_ZOne\main_qualidade2.py", line 132, in <module>
    os.replace(path + file_name, "C:\\Users\\allan.mesquita\\NTT\\@AM BR Services and Operations - Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\03 Erro\\" + file_name)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\allan.mesquita\\NTT\\@AM BR Services and Operations - Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\Testes\\01 Processamento\\202204051510 33220305437734000580550010000026611100018356_Expedição.xlsx' -> 'C:\\Users\\allan.mesquita\\NTT\\@AM BR Services and Operations - Privado\\GESTÃO DE ESTOQUE\\100 BcoDados\\003 Evidencias\\06 Lixeira\\03 Erro\\202204051510 33220305437734000580550010000026611100018356_Expedição.xlsx'
